import type { Annotation } from './annotation';
import type { Audio } from './audio';
import type { ToolCall } from './tool-call';

/** OpenAI标准聊天消息 */
export interface ChatMessage {
  /** The role of the author of this message */
  role?: 'system' | 'user' | 'assistant' | 'tool' | 'function';
  /** The contents of the message */
  content?: unknown;
  /** The name of the author of this message */
  name?: string;
  /** The refusal message generated by the model */
  refusal?: string;
  /** If the audio output modality is requested, this object contains data about the audio response */
  audio?: Audio;
  /** Annotations for the message */
  annotations?: Annotation[];
  /** The tool calls generated by the model */
  tool_calls?: ToolCall[];
  /** Tool call that this message is responding to */
  tool_call_id?: string;
}
